version: '3'

networks:
  inception:

services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    restart: always
  
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
  
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        db_name: ${db_name}
        db_user: ${db_user}
        db_pass: ${db_pass}
    expose:
      - "3306"
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: on-failure 
    
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/mmounib/data/wordpress
      o: bind
      type: none
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/mmounib/data/mariadb
      o: bind
      type: none
    