FROM debian:buster

#ARG db_name \
    #db_user \
    #db_pass

RUN apt-get update && apt-get install -y mariadb-server

RUN sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./tools/mariadb.sh /
#COPY ./conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf
#RUN sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf

#RUN mkdir -p /var/run/mysqld
RUN chmod +x mariadb.sh

EXPOSE 3306

CMD ["/mariadb.sh"]