version: '3'

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 443:443
    restart: always
  
  wordpress:
    build:
      context: .
      dockerfile: wordpress/dockerfile
    expose:
      - "9000"
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
  
  mariadb:
    build:
      context: .
      dockerfile: mariadb/dockerfile
    expose:
      - "3306"
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    # volumes:
    #   - test:/var/lib/mysql
    restart: on-failure
    
volumes:
  test:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /Users/mmounib/Desktop/Inception/wordpress_volume/
      o: bind
      type: none
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /Users/mmounib/Desktop/inception/mariadb_volume
      o: bind
      type: none
    