FROM debian:buster

RUN apt-get update && apt-get install -y php7.3 php7.3-fpm php7.3-mysql && apt-get install -y curl

RUN apt install -y mariadb-client
RUN mkdir -p /var/www/html
WORKDIR /var/www/html

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp && wp core download --allow-root

RUN mkdir -p /run/php
RUN mv /var/www/html/wp-config-sample.php /var/www/html/wp-config.php

COPY wordpress/www.conf /etc/php/7.3/fpm/pool.d
COPY /wordpress/wordpress.sh .

RUN chmod +x wordpress.sh

EXPOSE 9000

CMD ["./wordpress.sh"]