FROM debian:buster-slim

RUN apt-get update && apt-get install -y php php-fpm php-mysql && apt-get install -y curl

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

RUN chmod +x wp-cli.phar

EXPOSE 9000

CMD ["/usr/sbin/php-fpm7.3", "-f"]